services:
  minio:
    image: minio/minio
    container_name: minio
    hostname: minio
    restart: always
    ports:
      - 9000:9000
      - 9001:9001
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio
    volumes:
      - ./minio/data:/data
    command: server --console-address ':9001' /data
    networks:
      - shared_net:

  video-db:
    image: postgres
    container_name: video-db
    hostname: video-db
    restart: always
    ports:
      - 5433:5432
    environment:
      - POSTGRES_PASSWORD: root
      - POSTGRES_DB: video-db
    volumes:
      - ./postgresql/video-db:/var/lib/postgresql/data
    networks:
      - shared_net:

  processing-db:
    image: postgres
    container_name: processing-db
    hostname: processing-db
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_PASSWORD: root
      - POSTGRES_DB: processing-db
    volumes:
      - ./postgresql/video-db:/var/lib/postgresql/data
    networks:
      - shared_net:


networks:
  - shared_net: